# Generated by Django 2.2.6 on 2019-10-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_servicio', models.IntegerField(primary_key=True, serialize=False)),
                ('rut_cliente', models.CharField(max_length=12)),
                ('Nombre_completo', models.CharField(max_length=100)),
                ('fecha_de_visita', models.DateField()),
                ('hora_de_visita', models.CharField(max_length=5)),
                ('direccion', models.CharField(max_length=100)),
                ('preosupuesto', models.CharField(max_length=7)),
                ('descripcion_pc_a_solicitar', models.CharField(max_length=50)),
                ('desea_induccion', models.CharField(max_length=2)),
                ('numero_celular', models.CharField(max_length=8)),
            ],
        ),
    ]
