# Generated by Django 2.2.6 on 2019-10-30 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Armado', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitud',
            options={'permissions': (('tecnico', 'Es tecnico'),)},
        ),
    ]
