# Generated by Django 2.1.3 on 2019-11-10 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Armado', '0002_auto_20191030_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.IntegerField(primary_key=True, serialize=False)),
                ('rut_cliente', models.CharField(max_length=12)),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('rut_visitante', models.CharField(max_length=12)),
                ('nombre_visitante', models.CharField(max_length=100)),
                ('estado_pedido', models.CharField(max_length=2)),
                ('numero_celular', models.CharField(max_length=8)),
                ('fecha_de_despacho', models.DateField()),
            ],
            options={
                'permissions': (('tecnico', 'Es tecnico'),),
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.TextField(max_length=12, primary_key=True, serialize=False)),
                ('procesador', models.TextField(max_length=22)),
                ('placa', models.TextField(max_length=22)),
                ('memoria_ram', models.TextField(max_length=22)),
                ('tarjeta_video', models.TextField(max_length=22)),
                ('disco_duro', models.TextField(max_length=22)),
                ('modelo_gabinete', models.TextField(max_length=20)),
                ('precio', models.TextField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='solicitud',
            options={},
        ),
        migrations.AddField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(default=2, max_length=2),
            preserve_default=False,
        ),
    ]
