# Generated by Django 2.1.3 on 2019-11-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Armado', '0003_auto_20191109_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_de_visita',
            field=models.CharField(max_length=10),
        ),
    ]
