# Generated by Django 2.1.3 on 2019-11-10 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Armado', '0004_auto_20191110_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='estado',
        ),
    ]
