# Generated by Django 2.1.3 on 2019-11-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Armado', '0005_remove_solicitud_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_de_despacho',
            field=models.CharField(max_length=10),
        ),
    ]
