# Generated by Django 2.1.3 on 2019-11-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Armado', '0007_pedido_codigo_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='preosupuesto',
            field=models.CharField(max_length=9),
        ),
    ]
